### ISSUE TITLE
No need to use wait()

### ISSUE THREAD

**Issue by bahmutov** [jennvoss/tales-from-the-qa-crypt#2]
Great tests, just a little advice - you don't need to use `cy.wait(2500)` to wait for the success element to be removed. Just let Cypress retry until the element no longer is there. This will make the tests slightly faster, because it will continue as soon as the element is removed. Also I can factor out the check into a helper function like this

```js
  const popup = () => {
    cy.get('.success')
      .should('be.visible')
    // message disappears, but we should select it in the DOM again
    // because React re-renders everything, so the previous DOM element
    // is no longer there!
    cy.get('.success').should('not.exist');
  }

  it('Toggles a todo to incomplete', function() {
    cy
      .get('div.Todo-List > ul > li:nth-child(1) > input[type="checkbox"]')
      .should('be.checked')
      .click()
      .should('not.be.checked')
    popup()
  });
```

**Comment by jennvoss** [comment]
👍 thanks, I will refactor

**Comment by jennvoss** [comment]
Fixed in https://github.com/jennvoss/tales-from-the-qa-crypt/commit/914c1163cd9ca2d2022fe9b408485f59428ec1f8
